### ISSUE TITLE
Endless Cycle with Exception Handler when Crash Detection is enabled

### ISSUE THREAD

**Issue by itsJS** [at-internet/piano-analytics-apple#19]
**SDK Version:** 3.0.5

**iOS Version:** 16.0

**Xcode Version:** 15.0

**Device:** Real iPhone 13 & iPhone 15 Simulator

**Description:**

I have encountered an issue with the library where the exception handler appears to create an endless cycle when the iOS app encounters an exception. That means, when the app encounters an exception, the exception handler of Piano is called, which then encounters an exception, that exception causes the exception handler to be called again. This behaviour results in a call stack that becomes polluted with repeated exceptions, making it difficult to identify and diagnose the root cause of the problem that occurred initially.

**Steps to Reproduce:**

1. set `.enableCrashDetection(true)`
2. Force an exception in your project

**Expected Behavior:**

I expect the exception handler in the Piano library to gracefully handle exceptions and provide meaningful error information to assist with debugging.

**Actual Behavior:**

The current behavior involves an endless cycle where the app triggers an exception, the exception handler is called, and it, in turn, triggers another exception. This loop results in a polluted call stack and hinders effective debugging.

**Screenshots/Logs:**
<img width="840" alt="Screenshot 2023-10-16 at 17 25 44" src="https://github.com/at-internet/piano-analytics-apple/assets/34193571/076477bf-860c-488d-ab06-0e45d1b20c04">

Thank you for your attention to this issue. Please let me know if you need any further information or clarification.

**Comment by alexey-troshkov** [comment]
@itsJS Please show your stacktrace

**Comment by alexey-troshkov** [comment]
Fixed in version 3.0.7
