### ISSUE TITLE
3.1.0 with xcprivacy changes prevents building

### ISSUE THREAD

**Issue by felixspitzer** [at-internet/piano-analytics-apple#25]
![Screenshot 2024-06-04 at 08 15 28](https://github.com/at-internet/piano-analytics-apple/assets/55360637/7774d6d2-9a5e-4eb1-9764-e90bba4ce92c)

**Comment by felixspitzer** [comment]
I think the file should not be integrated like this. It should not be a resource that remains when building

**Comment by alexey-troshkov** [comment]
Set the "User Script Sandboxing" parameter to "No"
<img width="730" alt="screen" src="https://github.com/at-internet/piano-analytics-apple/assets/55428673/82787829-7b0a-477d-bc31-4d34f394a15d">

**Comment by rubenrdias-twipe** [comment]
We're also facing this problem, would be great to have a fix for it. Still not solved in `3.1.1`.

**Comment by alexey-troshkov** [comment]
PrivacyManifest would have been moved to bundle in v3.1.2, please check.

**Comment by rubenrdias-twipe** [comment]
This does seem to fix the problem on our side. Thanks!
