### ISSUE TITLE
Piano events not sending on recent iOS devices in 3.1.2

### ISSUE THREAD

**Issue by GregUAs** [at-internet/piano-analytics-apple#26]
Hello, I'm working on a Flutter app and I put PianoAnalytics in the native part of my app.

Until now, I've been using the Git version based on the main branch. 
I noticed that on version 3.1.2, only on iPhone 13/14/15, Piano events were not being sent.
When tested on less recent phones, such as an iPhone X version 15.x or an iPhone 6S version 13.x, the events are sent to the Piano interface.

I had to downgrade to version 3.0.10 to make sure it worked (the same version that's on my app in the Apple Store right now).

Thank you in advance !

**Comment by mmoser-hw** [comment]
Hello, we've had the same issue on our fully native app, so we can safely say Flutter is out of cause here.
We've also been forced to downgrade, but if we notice something else we'll share it with you.

Thanks in advance for any fixes.

**Comment by BenDz** [comment]
Hello,
The issue may stem from the fact that [`NSPrivacyTracking` is enabled by default](https://github.com/at-internet/piano-analytics-apple/blob/03cba14652fbd8e98bdc798d4550d037cbefd2b8/Sources/PianoAnalytics/Resources/PrivacyInfo.xcprivacy#L5) by our SDK.
This enables your app to comply with users' consent regarding tracking, using the [ATT framework](https://developer.apple.com/documentation/apptrackingtransparency).

To give our customers more control over their app's behavior, we are considering a change.
We welcome any suggestions you might have.

**Comment by BenDz** [comment]
Hello,
We just released `3.1.3` removing `NSPrivacyTracking` enabled by default.
https://github.com/at-internet/piano-analytics-apple/releases/tag/3.1.3
