### ISSUE TITLE
High energy consumption when in background

### ISSUE THREAD

**Issue by aregler** [at-internet/piano-analytics-apple#30]
Hello,

We're working on an audio app that supports background playback. Unfortunately, we're experiencing high energy consumption when playing audio in the background.

After debugging our app, we discovered that the Piano SDK seems to be contributing to this issue. Our PianoClient is wrapped in a custom dependency and uses the following method:

![image](https://github.com/user-attachments/assets/b2221c13-ac61-4a88-b709-539a3cc4ecba)

When we disable just the .track method, the energy consumption gauge in Xcode drops from "high" to "low."

![image](https://github.com/user-attachments/assets/b20e38f9-ba5f-4f4a-b95d-610b1eab73a1)

We're currently using version 3.1.7. It would be great if you could investigate this issue.
If you need any further information, please let me know.

**Comment by BenDz** [comment]
Hi @aregler 
Could you please tell us how often you call `.track` and what event names are used?
Here is our test sending 8 events (`av.buffer.start`) within 10 seconds
![image](https://github.com/user-attachments/assets/695373b8-a919-4f6d-ac47-2b569859886b)

Thanks

**Comment by aregler** [comment]
Hey @BenDz, we're sending a heartbeat every 10 seconds.

But looking at your test results I think the energy usage is quite "high". If you add other minimal activity like playback the gauge will just change to high.

**Comment by aregler** [comment]
Hi @alexey-troshkov. Agreed! I just removed the HTTP request code in SendStep, and everything seems fine. However, it’s still not optimal. According to the documentation, we can batch events manually, but I’d like to suggest that the Piano client should also offer an option for batching events. We can close the issue soon, but I’m curious about your answer.

**Comment by alexey-troshkov** [comment]
Hi @aregler. If you accumulate events and then send them via sendEvents([ev1, ev2, ...]) the scheduler will still send them sequentially, one request per event. We will discuss the possibility of sending events in a batch.

**Comment by aregler** [comment]
Alright, thank you.
