### ISSUE TITLE
Swift Package Manager - Can't load default.json

### ISSUE THREAD

**Issue by g012** [at-internet/piano-analytics-apple#7]
Hello,

If the library is imported using Swift Package Manager, it fails to load 'default.json' - it works with CocoaPods.

In Configuration.swift :
`fatalError("PianoAnalytics: a default config should be provided inside the framework")`

I do get a path for the file, something like `/var/containers/Bundle/Application/[uuid]/[appname].app/PianoAnalytics_PianoAnalytics.bundle/default.json`, but it doesn't load it. Maybe it's due to the way this path is built, using `Bundle(for: type(of: self))` - according to this page : https://developer.apple.com/forums/thread/650914 , for SPM only `Bundle.module` will work.

**Comment by MrJre** [comment]
See also https://github.com/at-internet/piano-analytics-apple/pull/1

**Comment by g012** [comment]
> See also #1

Indeed, my app name also has a space in it, and it gets encoded as %20 in the path variable.

**Comment by piano-analytics** [comment]
Hello,
This should be resolved with version 3.0.2  : )
