### ISSUE TITLE
Allow injecting url session protocol classes

### ISSUE THREAD

**Issue by fruitcoder** [at-internet/piano-analytics-apple#9]
In order to write UITests it would be advantageous to use custom protocol classes for the url session you use (i.e. for [Mocker](https://github.com/WeTransfer/Mocker) or similar tools). Currently, this is not possible because you aren't using the shared url session but create a custom one for every [SendStep](https://github.com/at-internet/piano-analytics-apple/blob/14480ba00584f6550d8572873fe6abe2500371fa/Sources/PianoAnalytics/Steps/SendStep.swift#L87).

There are two ways this could be solved:
1. Use the shared url session. You only set the `timeoutIntervalForResource` property on the url session configuration and you also set the `timeoutInterval` on the URLRequest itself which is redundant (the url session has a timer for the max time any bytes are received, the url request's timer is for the overall request time. If they are the same value the url requests timer is sufficient).
2. Allow injecting custom protocol classes and use those when creating a custom session. This would still give you the possibility to have a custom url session and tweak some properties in the future.

I created two PRs for the proposed solutions:

**Comment by alexey-troshkov** [comment]
Please see `PA.ExtendedConfiguration` https://github.com/at-internet/piano-analytics-apple/blob/main/Sources/PianoAnalytics/Core/ExtendedConfiguration.swift#L6 
and initialization https://github.com/at-internet/piano-analytics-apple/blob/main/Sources/PianoAnalytics/PianoAnalytics.swift#L444
